packages:
  - "demo"
  - "graph-image"
# Define a catalog of version ranges.
catalog:
  # build packages
  "typescript": "^5.7.2"
  "@sveltejs/kit": "^2.10.1"
  "svelte": "^5.5.2"
  "@sveltejs/package": "^2.3.7"
  "@sveltejs/adapter-auto": "^3.3.1"
  "@sveltejs/vite-plugin-svelte": "^5.0.1"
  "vite": "^6.0.3"
  "tslib": "^2.8.1"
  # testing packages
  "vitest": "^2.1.6"
  # linting packages
  "eslint": "^9.7.0"
  "@types/eslint": "^9.6.0"
  "typescript-eslint": "^8.0.0"
  "eslint-config-prettier": "^9.1.0"
  "eslint-plugin-svelte": "^2.36.0"
  "globals": "^15.0.0"
  "svelte-check": "^4.1.0"
  "prettier": "^3.4.1"
  "prettier-plugin-svelte": "^3.3.2"
