name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Pull Request Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install Dependencies
        run: pnpm install

      - name: Run Unit Tests
        run: turbo test
